FROM nvcr.io/nvidia/pytorch:26.06-py3

ARG DEBIAN_FRONTEND=noninteractive
 
# install the basics
RUN apt-get update \
 && apt-get install -y --no-install-recommends \
 vim \
 tmux \
 cmake \
 gcc \
 g++ \
 git \
 build-essential \
 sudo \
 wget \
 curl \
 zip \
 unzip
 
# add a user
ARG user_id
ARG USER jammy
RUN userdel ubuntu || true
RUN useradd -U --uid ${user_id} -ms /bin/bash $USER \
 && echo "$USER:$USER" | chpasswd \
 && adduser $USER sudo \
 && echo "$USER ALL=NOPASSWD: ALL" >> /etc/sudoers.d/$USER
 
#apply torch_tensorrt patch
RUN sed -i 's/^\(\s*\)if attn_bias\.dtype == trt\.DataType\.BOOL:/\1attn_bias = get_trt_tensor(ctx, attn_bias, name + "_attn_bias")\n\1if attn_bias.dtype == trt.DataType.BOOL:/' \
    /usr/local/lib/python3.12/dist-packages/torch_tensorrt/dynamo/conversion/impl/attention.py
USER $USER
WORKDIR /home/$USER 
 
RUN sudo apt install -y python3-pip
RUN pip3 install --no-deps opencv-python-headless ultralytics

RUN sudo apt update \
 && sudo apt install -y \
 libopencv-dev \
 libjsoncpp-dev \
 libgtest-dev 

RUN echo 'export PS1="\[$(tput setaf 2; tput bold)\]\u\[$(tput setaf 7)\]@\[$(tput setaf 3)\]\h\[$(tput setaf 7)\]:\[$(tput setaf 4)\]\W\[$(tput setaf 7)\]$ \[$(tput sgr0)\]"' >> ~/.bashrc
