FROM sam3-tensorrt:infer

ENV DEBIAN_FRONTEND=noninteractive
ENV ROS_DISTRO=jazzy
ENV LANG=en_US.UTF-8

RUN sudo -E apt-get update && sudo -E apt-get install -y --no-install-recommends \
        locales software-properties-common curl ca-certificates \
    && sudo locale-gen en_US en_US.UTF-8 \
    && sudo update-locale LC_ALL=en_US.UTF-8 LANG=en_US.UTF-8 \
    && sudo add-apt-repository -y universe

RUN export ROS_APT_SOURCE_VERSION=$(curl -s https://api.github.com/repos/ros-infrastructure/ros-apt-source/releases/latest | grep -F "tag_name" | awk -F'"' '{print $4}') \
    && curl -L -o /tmp/ros2-apt-source.deb \
       "https://github.com/ros-infrastructure/ros-apt-source/releases/download/${ROS_APT_SOURCE_VERSION}/ros2-apt-source_${ROS_APT_SOURCE_VERSION}.noble_all.deb" \
    && sudo dpkg -i /tmp/ros2-apt-source.deb \
    && rm /tmp/ros2-apt-source.deb

RUN sudo -E apt-get update && sudo -E apt-get install -y --no-install-recommends \
        ros-jazzy-ros-base \
        ros-dev-tools \
        python3-rosdep \
        python3-colcon-common-extensions \
    && sudo rm -rf /var/lib/apt/lists/*

RUN sudo rosdep init && rosdep update

RUN sudo apt update \
 && sudo apt install -y ros-jazzy-rmw-zenoh-cpp ros-jazzy-rqt*
ENV RMW_IMPLEMENTATION=rmw_zenoh_cpp
ENV ROS_AUTOMATIC_DISCOVERY_RANGE=LOCALHOST

RUN mkdir -p ws/src 
RUN echo "source /opt/ros/jazzy/setup.bash" >> ~/.bashrc
